### ISSUE TITLE
Use RSS/Atom instead of JSON?

### ISSUE THREAD

**Issue by ktheory** [madrobby/downtime#1]
Some status sites already offer RSS feeds as a programatic way to check application status (e.g. [heroku](https://status.heroku.com), [AWS](http://status.aws.amazon.com)).

RSS has well-known auto-discovery features.

If you're starting simple with your status site by using a publishing tool (Tumblr, Wordpress, Twitter etc), you get RSS for free. Downtime in json would require extra work.

OTOH, JSON is a lot easier to parse than XML. What other advantages does downtime provide over RSS/Atom?

Maybe the real challenge is creating a microformat for describing downtime.

**Comment by madrobby** [comment]
I'd rather use a really simple JSON API. We could have a converter that reads Atom and generates downtime JSON, probably pretty easy to fix up.

Thomas
http://script.aculo.us/thomas
http://slash7.com/company

**Comment by madrobby** [comment]
The main reasoning is that it's easy to generate JSON if you already generate RSS, and you can write it easily by hand as well, which is probably what most smaller sites might do. Additionally, we can provide a HTML template that loads the downtime JSON file and generate a nice human-facing status page for free.

**Comment by westurner** [comment]
1. There are many existing tools for aggregating RSS/ATOM.
2. For including structured data in HTML, there is microdata. Schema.org is a well-supported set of microdata formats. (#10)

**Comment by madrobby** [comment]
I don't want the overhead of having to deal with XML, and this is not about embedding metadata in HTML.
