### ISSUE TITLE
Use rfc5785 path prefix?

### ISSUE THREAD

**Issue by timcraft** [madrobby/downtime#2]
So the location would be `/.well-known/downtime.json` instead of `/downtime.json`

More infos: http://tools.ietf.org/html/rfc5785

Thoughts?

**Comment by westurner** [comment]
+1

**Comment by madrobby** [comment]
I've not seen this in the wild. If it gets wide adoption, we can do this perhaps but there are downsides, like the dot file name hiding the folder from people's editors. Judging from the registry for this, it seems to be academic and not very useful.
