### ISSUE TITLE
Unscheduled future downtime

### ISSUE THREAD

**Issue by timcraft** [madrobby/downtime#3]
The readme says "The file shouldn't contain events in the past", but the example indicates that there can be "unscheduled" events listed.

I might be missing something, but how do you know when future downtime will be if it is unscheduled :interrobang:

**Comment by madrobby** [comment]
You don't, you just add an entry with started_at set to now when unscheduled downtime occurs.

Thomas
http://script.aculo.us/thomas
http://slash7.com/company
