### ISSUE TITLE
Leave out eol

### ISSUE THREAD

**Issue by aeden** [madrobby/downtime#4]
It seems like EOL of an API doesn't really fit with this. The rest of the idea is neat though.

**Comment by madrobby** [comment]
True, maybe it's something for a V2 tho. I'd love to know about things like EOL'd API end points and feel that that's a very related problem and could share some of tool chain at least.

**Comment by aeden** [comment]
The notion of downtime seems like a temporary operational state, whereas API EOL is more of an API documentation/versioning issue.

**Comment by madrobby** [comment]
done!
