### ISSUE TITLE
Thoughts on non-HTTP services?

### ISSUE THREAD

**Issue by aeden** [madrobby/downtime#7]
Any thoughts on how I would represent DNS service downtimes if necessary?

**Comment by madrobby** [comment]
Hmm, perhaps something like `dns://server.domain.tld:53` — is there a URI format that can point to DNS servers/entries?

**Comment by aeden** [comment]
Maybe this: http://www.rfc-editor.org/rfc/rfc4501.txt

**Comment by aeden** [comment]
Closing due to old age.
